### PR TITLE
clarify that it must also be marked in the repository

### PR DESCRIPTION
**Pull request by voldemortensen**

### CODE REVIEW

**Comment by Ipstenu** [comment]
Technically you don't HAVE to mark a version as stable. If you don't, it defaults to trunk. Is this just to remind people of how to use SVN or is there an actual issue you've seen?

**Comment by voldemortensen** [comment]
Just as a reminder. I've never seen an issue (other than my own mistakes that is).

**Comment by Ipstenu** [comment]
It's actually not correct either as I think about it. We distribute any version you've checked into SVN. WP-CLI for example can download specific versions for you. Since we say a stable version must be available from your directory page, it implies that the readme has to be right, otherwise you won't have a stable version. What if we changed that to a link at the end? "See also: [How your readme.txt controls what is displayed on the directory](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/)" or such?

**Comment by Ipstenu** [comment]
Closing this for now as it feels not the right place for this information. Revisiting/reopening is welcome though :)

**Pull request closed without merging**
