### PR TITLE
Remove problematic license declarations and clarify

### LINKED ISSUE #10: “Considered GPL”
> Without a license.txt file, or referencing and/or declaring a license within code comments or a readme.txt file, the plugin and all its components are considered GPLv2 or later.

> https://github.com/Ipstenu/wporg-plugin-guidelines/blob/master/guideline-02.md

Repository has no power to “consider” licenses upon third party code.

It can, of course, set and enforce license rules.

However _assuming_ licenses is baseless practice, which is dangerous to downstream consumers. 

Repository **cannot** promise that what I download is GPLv2+ if **its developer did not make it so**.

Repository **can** remove code for non–compliance, but it **cannot** make licensing decisions about it. Only developer / copyright holder can.

### PR DESCRIPTION
**Pull request by Ipstenu**
* Combine Guidelines 1 & 2
* Change 2 to clarify ‘Don’t upload stuff you don’t have the right to upload, and if you can’t confirm licenses’

Props @rarst

Resolves #10

### CODE REVIEW

**Comment by Ipstenu** [comment]
I agree 'right to upload' is redundant, and yet it's a bit of a CYA for us. It should never come up but it has before.

**Comment by jeremyfelt** [comment]
Chiming in with a 👍  for requiring an explicit license declaration rather than a default.

This could be a documentation issue for another time, but it may be helpful to provide best practice examples for how attribution/licensing is included for 3rd party libraries.

**Comment by Ipstenu** [comment]
I think I can do a scan of the repo... Find me all `readme.txt

**Comment by Ipstenu** [comment]
FYI: 50% of the most popular plugins don't declare a license.

*SIGH* Well this will be entertaining. Anyway. Some of this can be addressed in code, so as long as the point of G1 and G2 comes across as "Don't upload things you're not suppose to upload, either because they're not GPL or you don't have permission." then I think we're covered.

**Comment by Rarst** [comment]
Hm hm... I think there is a bit of ambiguity with "or later" thing. It can be read two ways:

1. Compatible with any one version of GPL
2. Compatible with GPLv2+ (that is compatible with GPLv2 **and** GPLv3)

That's why I suggested _less_ specific "compatible with GPL" wording.

**Comment by Ipstenu** [comment]
Both are valid though, aren't they?

You can declare a plugin GPLv3 or v2. Plus this creates parity with https://wordpress.org/about/license/

**Comment by Rarst** [comment]
> You can declare a plugin GPLv3 or v2.

Yes, it's case (1) of reading it. Case (2) is incompatible with this.

GPLv2+ aka "GPLv2 or later" (like core has) is more restrictive. Neither GPLv2 strict or GPLv3 strict are compatible with GPLv2+ (as in they can't go _into_ GPLv2+, but they can be extracted from).

Compatibility with GPLv2+ is much higher bar than compatibility with GPL (v2 or v3),

More clear wording would be "GPL (any version, two or later).

**Comment by Ipstenu** [comment]
Okay, changed to "GPL (any version, two or later)"

Also put in a more clear phrasing in G2 of "Developers are responsible for what they upload" - Should be obvious, history proves it's not.

**Comment by Otto42** [comment]
I disagree with the changes made to guideline number 1.

It is not necessary for a plugin to declare a license, and changing the rules to force them to do so is unwarranted.

**Comment by Rarst** [comment]
> It is not necessary for a plugin to declare a license, and changing the rules to force them to do so is unwarranted.

Asking for specific licensing requires license applied. It's both or none, there is no halfway here.

**Comment by Otto42** [comment]
Certainly there is. Licensing is not a technical process like you seem to think it is.

A license is just the rules by which you can use some piece of work. If the author of that work says a license, then that's the license. 

If the author of the work literally doesn't care how the work is used, then it doesn't make any difference. 

But if the author of the work uploads their work to the repository which states "all work uploaded here must be GPL compatible", then they're taking an action which implies that it is GPL-Compatible. 

For years you have made this objection, and I still do not understand it. You're wrong about licensing. Licenses do not have to be explicitly stated.

**Comment by Rarst** [comment]
> Licensing is not a technical process like you seem to think it is.

Licensing is _absolutely_ a technical process. It's a _legal instrument_, based on _law_. It's not just some friendly agreement people made up.

> A license is just the rules by which you can use some piece of work. If the author of that work says a license, then that's the license.

A license needs to be _applied_ to a piece of work. Author saying stuff is sort of a thing in casual setting, but any significant work needs this to be done properly. "Author said stuff" is poor excuse when someone gets sued.

> But if the author of the work uploads their work to the repository which states "all work uploaded here must be GPL compatible", then they're taking an action which implies that it is GPL-Compatible.

This is just a thing you made up. Please see [How to use GNU licenses for your own software](https://www.gnu.org/licenses/gpl-howto.en.html) for GNU's own opinion on how GPL should be applied to a work.

> You're wrong about licensing. Licenses do not have to be explicitly stated.

I understand that for you it's all about "spirit" of GPL and stuff. I ask _you_ to understand that for other people this is matter of law and business. When you promote loose “whatever” attitude to licensing you are scaring off people who need legal certainty to use code their business will depend on.

**Comment by Otto42** [comment]
Regardless of your opinion on this matter, the gudieline is currently factually incorrect. The plugin directory does not require licenses to be explicitly stated in plugins. We encourage it, and we recommend it, but we do not require it.

Therefore, guideline 1 can not be implemented on WordPress.org in this form.

**Comment by Ipstenu** [comment]
>  We encourage it, and we recommend it, but we do not require it.

and

> The purpose of this guideline review is to reword them for clarity, not to change the rules. 

Okay. That's fair. The plugin team is also discussing the enforceability of requiring a license as that sort of thing would need to be a technical action since humans will miss. And not as many plugins omit a license declare as we'd feared. But since that will take quite a while to sort out, it would be premature to change the horse mid-stream.

"1. Plugins must be compatible with the GNU General Public License v2, or any later version to be hosted on WordPress.org."

We can all agree with that part I think, yes?

This is not a 'GPL' argument, we're just saying if you want to be on .org's hosting, you MUST be compatible.

Now this:

>> But if the author of the work uploads their work to the repository which states "all work uploaded here must be GPL compatible", then they're taking an action which implies that it is GPL-Compatible.
> This is just a thing you made up.

Okay, Rarst, I see your point but you're missing Otto's.

YES it's a thing he made up, that's called the GUIDLINE. We're telling, as we always have, if you upload code, it has to be GPL compatible, and by uploading, you're confirming it is. Really it's not to do with license compatibility here, but a user level agreement.

I _think_ the rephrasing in G2 ('you're responsible for what you upload') is a bit of a middle road. It's not saying 'We're MAKING it GPLv2 or later' -- instead it's saying 'YOU are accepting responsibility for all the guidelines, and that your code meets them.' Same idea, different presentation. That way we obviate the argument of if we have the right to declare a license in absentia (INAL!) or if we can CYA.

**Comment by Ipstenu** [comment]
See https://github.com/Ipstenu/wporg-plugin-guidelines/commit/e2fd57b7e5038f4fb0ecc0d7dab874e1309a7109

Trying to find a medium between the intent (agreement to our ToS  which is 'all your code has to be compatible') and the argument of illegality of declaring it for you in our ToS. I _think_ the middle is saying it has to be GPL, and you're accepting responsibility for everything you upload and connect to in your plugin, so if you violate any guideline (including the aforementioned GPL) we hit you with a brick. 🗿

**Pull request merged**
