### PR TITLE
Change plugin guidelines to prohibit ads except on own pages

### PR DESCRIPTION
**Pull request by mbootsman**
Updated the text so there is no discussion possible. No ads except on your own (settings) pages in the admin.

### CODE REVIEW

**Comment by nicomollet** [comment]
Very much needed after a wave of black friday ads in our dashboards.

**Comment by Eugene-Chernetsky** [comment]
Kudos!
I think our corporate site had been hacked when I saw ugly Yoast SEO animated banner

**Comment by ifrountas** [comment]
We should definitely do this!

**Comment by Ipstenu** [comment]
As much as I personally want to stamp this and shout yes, the last time I proposed it I was reminded of the biggest issue.

Not all plugins (in fact, not _most_ plugins) have admin panels. This sort of guideline change would result in an unfair advantage in business being handed over to only the plugins with their own panels.

Also the line between an ad and an alert is so wafer thin, that it requires a lot of human work to manage and monitor. Work no one is willing to do on an extended basis.

I'm going to leave this open, though, because if the passionate people here can think of a way to balance this better, I want to know. Right now, though, it's a non-starter because it would just create more unfairness :(

**Review by multimedianj — APPROVED** [review]

**Comment by xsonic** [comment]
@Ipstenu thanks for the input. Much appreciated.

I agree on the thin line between alert and ad, and I have currently no idea how this could be solved via finetuned wording. But maybe we could add something like "if you feel you must advertise on the dashboard, it is highly encouraged to do so in an unintrusive way [...]", but again, unintrusive is highly debatable.

Or maybe just allow wordpress notice-styling.

I think a decent advertisment in wordpress styling wouldn't have caused such an outrage, but Yoast, in fact, placed an animated banner that overlaps the top buttons ("more options" etc.), and highjacks the cursor.

Also, plugins without setting screens can still advertise on the plugins page (as many do now anyway).

**Comment by ifrountas** [comment]
@Ipstenu I can see your viewpoint and to be honest, you are absolutely right. But on the other hand we need to take an action for the notifications within the WordPress dashboard in general (banners and ads either).

I see often dashboards like this one https://twitter.com/froudas/status/1181292011560800263 whether notification is an ad or not.

So, wouldn't it be great to have a separate notification page for all types of notifications?

**Comment by wpchannel** [comment]
@Ipstenu yes maybe but as mentioned by @ifrountas something has to be done. We should not preserve status quo.

**Comment by jfarsen** [comment]
... maybe... if a plugin developer wants to add ads to their plugin, creating an admin panel for their plugin is the "entry fee"?

Adding a settings panel to a plugin isn't rocket science, in the grand scheme of things.

**Comment by JulioPotier** [comment]
@Ipstenu
if ( you add a notice where you want to promote a product ) {
  $this = $ad;
} else {
  $this = $alert;
}

also

if ( you add a notice everywhere in the admin area ) {
  "I hope this is urgent or important and dismissible"
} else {
  "really??"
}

**Comment by Eugene-Chernetsky** [comment]
> Not all plugins (in fact, not _most_ plugins) have admin panels

So at Black Friday 2020 we will see our admin dashboards overfilled by tens and tens of banners from plugin developers?

Is that ok?

**Comment by ifrountas** [comment]
> @Ipstenu
> if ( you add a notice where you want to promote a product ) {
> $this = $ad;
> } else {
> $this = $alert;
> }
> 
> also
> 
> if ( you add a notice everywhere in the admin area ) {
> "I hope this is urgent or important and dismissible"
> } else {
> "really??"
> }

@JulioPotier With these functions we need to check every single plugin update to see if it violates them.

Despite that is a good practice in theory, in practice it could add tons of work to the community members who are responsible for plugins.

**Comment by Otto42** [comment]
> > Not all plugins (in fact, not _most_ plugins) have admin panels
> 
> So at Black Friday 2020 we will see our admin dashboards overfilled by tens and tens of banners from plugin developers?
> 
> Is that ok?

Have you considered voting with your feet and simply uninstalling plugins that do things you don't like? Alternative plugins are almost always available.

Realistically, trying to monitor and set these kind of heavy rules and regulations on what is permissible or not is ineffective. The presence of an advertisement may upset you, but it may be useful to some others who want that product or deal. Trying to limit the scope and reach of what plugins are allowed to do is just going to make them find ways to walk around the rules, or simply to not host their plugins in the directory. Driving away devs from the directory to other alternative directories isn't the best action for the ecosystem as a whole.

If plugin add excessive amounts of notices to the point where it is bad for you, then *don't use them anymore*. This sends the exact right message to the plugin author and produces the most effective result.

**Comment by JulioPotier** [comment]
@ifrountas 
This is a reminder for every plugin developer to know if it's an ad or an alert. This is not for wporg team when reviewing. Devs are still allowed to bypass the rules and take their chances.
But if they don't respect the guidelines: out until fix is done.

**Comment by pyronaur** [comment]
> Have you considered voting with your feet and simply uninstalling plugins that do things you don't like? Alternative plugins are almost always available.

+9000

**Comment by JulioPotier** [comment]
@Otto42 Could you link us 3 tweets or 3 comments somewhere where people are happy with this banner? I'll leave you alone. Thank you.

**Comment by JulioPotier** [comment]
> Have you considered voting with your feet and simply uninstalling plugins that do things you don't like? Alternative plugins are almost always available.
(poke @justnorris)

There is a difference between uninstalling a plugin because they do something I don't want VERSUS they do something they shouldn't even think about it, like, placing an yellow blinking ad in every dashboard page for every role for 7 days… see?

**Comment by Otto42** [comment]
> @Otto42 Could you link us 3 tweets or 3 comments somewhere where people are happy with this banner? I'll leave you alone. Thank you.

I don't need to show people happy about the banner, the amount of sales he likely made from the few hours it was there very likely speaks for itself.

My point is still that if the plugin upsets you, uninstall it. Other plugins are available. Many of them are quite good.

**Comment by Ipstenu** [comment]
A couple things and then I'm going to go away because it's a Holiday here :)

Yes, we need to do 'something' about ads because they're abused by many people.

WordPress _core_ (not Plugins a team, core) has no API or notifications section, so people do what they want. But... Even if they did, by simply being hookable and actionable, people would still do this.

We gave everyone the freedom to do everything they want. This comes at a cost, and sometimes the cost is 'annoying ads.'

So if someone can write up a fair GUIDELINE (not a code check, a guideline anyone can read and understand) that explains the difference between and okay ad and a non-okay one, please do. I've tried and failed. Where we sit today is a 'best judgement by the people enforcing this' and a 'freedom to do what you want, even if it's pissing off your customers'

Also you should know that voting with your feet had the desired effect: https://twitter.com/MariekeRakt/status/1200077958700044290

**Comment by JulioPotier** [comment]
@Otto42 Of course they will sell, so, making money allows developers to add banners like that. Good point to know.

**Comment by Otto42** [comment]
> `Have you considered voting with your feet and simply uninstalling plugins that do things you don't like? Alternative plugins are almost always available.`
> There is a difference between uninstalling a plugin because they do something I don't want VERSUS they do something they shouldn't even think about it, like, placing an yellow blinking ad in every dashboard page for every role for 7 days… see?

No, I don't see. Placing ads in the dashboard is discouraged, but permitted. In this particular case, it was a bad idea and got bad reception because of a lot of factors. Timing, placement, functionality, etc. But it didn't break any rules and the rules shouldn't be changed to disallow the whole idea because of it. 

Lots of plugins have advertised special deals in the past, and many will continue to do so in the future. We require that such notifications be permanently dismissible, and we recommend that they not be annoying. This one failed the last part of that, but that is a recommendation.

Plugin authors are allowed to shoot themselves in the foot.

**Comment by JulioPotier** [comment]
@Otto42 Ok got it. Thanks

**Comment by nicomollet** [comment]
But the current guidelines are too subjective and subject to interpretation.
Plugins developers think they interpret their way and have the right to publish ads without any kind of limit (duration, size, roles, animated or not).

**Comment by Eugene-Chernetsky** [comment]
> trying to monitor and set these kind of heavy rules and regulations

Is not-to-defecate into admin panel really heavy rule to keep on?
I can't believe

Fact is that case could be precedent and set common practice of spam adv into dashboard.
You will see dashboard filled by 5-7 banners everyday instead productive work.

THAT IS "isn't the best action for the ecosystem as a whole"

I can't believe (again!) I should explain such simple things to adult human!

That should be stopped here and now.

**Comment by afragen** [comment]
I am thankful that there are so many passionate people helping to make WordPress better.

Happy Thanksgiving everyone!

**Comment by Eugene-Chernetsky** [comment]
> Ok got it. Thanks

Now kiss

**Comment by Screenfeed** [comment]
>- Some companies are polluting the river with toxic waste and people get sick, we will ask these companies to recycle it internally.
>- But it will result in an unfair advantage in businesses that don't own a factory. Moreover, people just need to stop drinking water from the river and eating vegetable near the river if they don't want to get sick.
>- Oh, you're right.

**Comment by mintplugins** [comment]
@Otto42 I completely agree about voting with your feet. One thing that makes it difficult for people to do that, is that sometimes it's difficult to know where the banner originated, and that takes an investigation by the site owner. 

If we are considering a best-practice guideline, I would consider something like this:

## Notification Indicator Guidelines:
- **Origination**: Admin notifications that live _outside_ a plugin's own settings page(s) should indicate from which plugin/theme they originated (to make it easy to foot-vote). 

- **Purpose**: The notification should indicate its purpose, which should be one of these predefined values:
  - Advertisement
  - Security
  - Tip
  - Requirement
  - Misc
  - Other
  - Your idea for other standardized "purpose" labels here

- **Style**: The way they indicate this should follow a specific style, for which CSS classes could be added in WP core so the standard is easy to follow. That standard style could be something like this:
  - The notification indicator should be visually touching the notification itself, so that it is easy to see what it refers to.
  - It should share the same style across plugins. The same background color, border, font size, font color, layout, and more. 

## Visual example:
Screen Shot 2019-11-28 at 12 01 18 PM

This would help to empower people to easily "vote with their feet" if they find something to be problematic enough, without requiring them to go through the process of deactivating every plugin one-by-one just to find it. 

Of course, like all guidelines, this isn't something anyone can truly enforce, but it would at least be a guideline that people can follow. I think it serves everybody while keeping a level playing field.

**Comment by Screenfeed** [comment]
Now I'm sooooooo curious to know in which way my comment is ~censored~ "disruptive content" =)

**Comment by Ipstenu** [comment]
@Mamky-Ebal Your 'now kiss' comment is entirely inappropriate and unwelcome.

@Screenfeed Your red-herring argument (attempting to associate human lives lost to toxic waste as being the same as ads you don't like in plugins) is non-constructive.

Everyone. Please try to be constructive. Respect people as humans. Offer ideas. Don't attack people, or ideas for that matter.

**Comment by BrookeDot** [comment]
> The presence of an advertisement may upset you, but it may be useful to some others who want that product or deal.

From @Otto42  made consent come to my mind. While moderating plugins that use ads is a problem, I agree with others who have said most plugin developers know what is an "ad" and what is a "notification". What if the guideline was to provide an opt-in (or even an opt-out) for any advertisements. 

We could then define ads as "The promotion of additional services either free or paid that are not essential to the functionality of the plugin".

**Comment by daveloodts** [comment]
I personally don't think it's okay to place ads outside own plugin pages, and mostly not on the dashboard screen. 
It just creates an unprofessional look that will impact the WordPress image.

Problem is: plugin and theme builders have not much other options right now; certainly those who have no setting pages. And by the way: who is visiting the settings page anyway once it's installed?

A suggestion:
**What about a fixed Dashboard widget where plugin/theme authors can hook into.**
By fixed i mean: for example left upper corner. 
The widget can have tabs like: Promotions, News, Changelogs,
So, combining this widget with other interesting stuff like centralizing changelogs; it would be nicer to have it always in sight. 

Plus points:
- handy & central for the user
- in case of Back Friday: all promotion in one place
- professional look and straighter guidelines (wanna display banner? use the dashboard widget)
- (almost) the same promotion possibilities for every installed plugin/theme.

To counter the "what ifs":
- what if everyone else puts stuff in that widget?
  Yes, but what if everyone else puts banners in admin-pages. Image the average site has 20-25 plugins. Not every theme/plugin will launch promotions. In the end, it will be 5 to 10. Which is perfectly fittable in a dashboard widget. 

- how will we order the news/promotions in the widget?
Really don't know. But we can limit the number of displays per plugin/theme to 1. And listings must have a start- and endate with max. number of days between it. 

So, i hope this is a constructive idea.

Today, it was not the first discussion about 'unwanted' ads. 
And it won't be the last until there's no real solution.

I perfectly understand plugin/theme authors in this, trying everything to make a sell. And guidelines is (for some) multi intepretable.
And for the community, it's in their best interest that a plugin/theme author gets good/better 'selling'-opportunities as some money will flow back to meetups and wordcamps. I've been on WordCamps where 75% are hosting companies. See what i'm trying to say here... 

So far my idea 
and sorry for my bad english :-)

Happy Thanksgiving US!

**Comment by Screenfeed** [comment]
> @Screenfeed Your red-herring argument (attempting to associate human lives lost to toxic waste as being the same as ads you don't like in plugins) is non-constructive.

Ha ha ha, really? In France we say "foutage de gueule", and I think it’s beautiful.
OK, I'll do the same as some others already did in this thread, by just leaving you at your non action and whishing good luck 😘

**Comment by JeremyEnglert** [comment]
> Have you considered voting with your feet and simply uninstalling plugins that do things you don't like? Alternative plugins are almost always available.

Realistically, that's not always as easy as it sounds. This also leads to plugins being "ad free" until they build a large user-base and start plastering ads all over the dashboard. And it's not always as easy as just switching to an alternative.

> Driving away devs from the directory to other alternative directories isn't the best action for the ecosystem as a whole.

Will limiting advertising scare away some developers? Maybe. But WordPress is so large, that other developers will step in to fill those voids. I'd argue the WordPress dashboard becoming an advertising platform is much more damaging to the ecosystem. 

Also, there's other ways to promote premium features that don't involve plaguing the dashboard with banner ads and notices. 

It won't be an "easy" thing to fix. But today was the tipping point for a lot of people.

**Comment by Otto42** [comment]
> **What about a fixed Dashboard widget where plugin/theme authors can hook into.**

Plugins are allowed to add their own dashboard widgets, and I've recommended this to many authors in the past. These are easily hidden by the user and there's a whole interface in the code to add them.

**Comment by daveloodts** [comment]
@Otto42 Yep, of course users will hide it. It adds no value and will become annoying if the author always uses it as promotion. And 5 separate extra widgets is even more annyoing; instead of 5 authors in 1 widget; right.

But if we create a more interesting Dashboard widget with options like changelogs, wp news; that would work.

**Comment by codebard** [comment]
I strongly disagree with the proposition of limiting any such notice/upsell/ad to own pages of plugins.

Its necessary to be able to upsell plugins for many who use free + addon model. Also freemium model requires upsells. 

And as users, we all know that after we set up a plugin properly, it takes months for us to ever need checking a plugin's admin/settings page. If we check at all in a given year.

So a limitation as proposed would end up making it nigh impossible for people to do upsells and do a lot to cripple free + addon and freemium models to a great degree.

It is fundamental that we grow our ecosystem to stay free and not get undone by traditional, non-open source players who are seeking to consolidate CMS market. The free, participatory lifestyle we got accustomed to in WP ecosystem is dependent on well being of all segments that contribute to the ecosystem. Plugin houses which subsist on plugins constitute a large contributor to that well being. Not to mention that everyone needs to make a living.

I am very much in favor of the current WP guideline which goes in the form of "You can upsell one particular product once with a notice that shows across all admin pages. As long as the ad/notice for that particular product is relevant, does not repeat and you dont show more than one such notice per week" - or something like that. 

It seems to be working great at this moment, and there is no need to change it because one plugin author have done a mistake. 

We already have difficulty in contacting users for anything via built in WP features with any detailed information, and we have to resort to mailing lists and other things to make do. Not that users are actively seeking to get any information on anything that is happening - i doubt that a noticeable number check plugin change logs by merely clicking the plugin info in plugin manager before updating a plugin, even. 

Lets not make communication more difficult.

**Comment by sybrew** [comment]
To compile what @mintplugins and @daveloodts said into something that's already proposed:

1. Implement this https://core.trac.wordpress.org/ticket/43484
2. When plugins register notifications, let them add flags: 
   1. Type: "success, info, warning, alert, error, **advertisement**."
   2. Capability: `install_plugins`, `edit_posts`, etc.

And then force all ads to reside there. At most once per plugin at a time.

Of course, plugins will spawn that are going to filter out all notices with the "advertisement" flag. But it's something most users won't consider, yet it gives a concise path to opt-out globally.

Honestly, if this was implemented as such, even I'd feel compelled to start advertising via my now ad-free plugins, because I won't feel ashamed or obtuse.

**Comment by codebard** [comment]
> To compile what @mintplugins and @daveloodts said into something that's already proposed:
> 
> Honestly, if this was implemented as such, even I'd feel compelled to start advertising via my now ad-free plugins, because I won't feel ashamed or obtuse.

This feels like it would lead to a lot of spam and subsequent disablement of the advertisement notice type by a majority of users if non-relevant ads were allowed. Therefore rendering that notice useless. Like a plugin advertising web hosting or some other non-relevant plugin - that doesnt feel like non relevant ads could be allowed.

Then again if the ads are forced to be relevant, there is little difference compared to the info notice type. I dont see many people using info notices. What is a context for using that anyway, telling the user that "You look great today" as an information or something...

**Comment by JulioPotier** [comment]
ok so. Not everyone will agree with the chosen solution, but still, we have to do one and try. Just refusing everything won't do the thing. Just saying.

**Comment by djekanovic** [comment]
> As much as I personally want to stamp this and shout yes, the last time I proposed it I was reminded of the biggest issue.
> 
> Not all plugins (in fact, not _most_ plugins) have admin panels. This sort of guideline change would result in an unfair advantage in business being handed over to only the plugins with their own panels.
> 
> Also the line between an ad and an alert is so wafer thin, that it requires a lot of human work to manage and monitor. Work no one is willing to do on an extended basis.
> 
> I'm going to leave this open, though, because if the passionate people here can think of a way to balance this better, I want to know. Right now, though, it's a non-starter because it would just create more unfairness :(

I think simple solution would be that alerts are still only text based. And ads as in yoast example is gif or image. So based on that it can be sorted, to display alerts on homepage, but ads only in settings page.

**Comment by JulioPotier** [comment]
@djekanovic ho good idea. Strip images from every notice on native WP pages, but not on custom pages. NOICE.

**Comment by Eugene-Chernetsky** [comment]
> Your 'now kiss' comment is entirely inappropriate and unwelcome

My boy, you will be shocked if I say translation of my nickname!

**Comment by Otto42** [comment]
> @Otto42 Yep, of course users will hide it. It adds no value and will become annoying if the author always uses it as promotion. And 5 separate extra widgets is even more annyoing; instead of 5 authors in 1 widget; right.

Users will hide it? Apparently, they can't be bothered to click on the dismiss links at present, so I have my doubts about this notion.

**Comment by mbootsman** [comment]
https://github.com/WordPress/wporg-plugin-guidelines/pull/69#issuecomment-559533191

@Ipstenu Thanks for this. Of course not all plugins have settings pages. I realized that, when I read your comment.

To work to an update of the guidelines, I would propose to change the text to something that says: `WordPress notices are for notices only. No advertisements are allowed in the notices.`

Monitoring this is IMHO something that can be done reactively and not pro-actively by scanning plugin updates.

**Comment by mbootsman** [comment]
https://github.com/WordPress/wporg-plugin-guidelines/pull/69#issuecomment-559543332
@Otto42 Not all users decide which plugins run on their site. (They should be, but that's another discussion). So to prevent the WordPress admin to be an ad billboard, stricter guidelines have to be used.

**Comment by JulioPotier** [comment]
> they can't be bothered to click on the dismiss links at present, so I have my doubts about this notion. — @Otto42 

Well, no. If I decide to hide a widget, I'll do it one time in one click.
If a plugin wants to push a dismissible notice containing an ad for every role on everypage with a buggy close button (confirmed by the team), I'll have to do it for each plugin, and for evey discount they want to push.
I think… it's… not the same… AT ALL. :|

**Comment by Ipstenu** [comment]
> I think simple solution would be that alerts are still only text based. 

A lot of ads are text-based, just putting that out there.

> To work to an update of the guidelines, I would propose to change the text to something that says: WordPress notices are for notices only. No advertisements are allowed in the notices.

This creates an unfairness, the same as a settings screen would.

1. Plugins who have a settings page can still advertise
2. Plugins who don't have a settings page will be unable to advertise.
3. Newer plugins are at a disadvantage and won't be able to grow the ecosystem (which we do need).
4. We would have to define exactly what an 'advertisement' is - is a pro-version recommendation one? What about if I try to do a thing and my plugin says "Hey, that feature is available in pro!"

Also what happens if they use other hooks and not the notices? 

Honestly I think what needs to happen FIRST is WordPress get the Notifications API done:

https://make.wordpress.org/core/tag/feature-notifications/

A LOT of work needs to happen - https://core.trac.wordpress.org/ticket/43484 - but once we have THAT we then have an easier way to direct developers.

Right now, demanding they take action to fix a problem we (core) won't is unfair, IMO.

(Yes, I feel the same way about people who have to use CMB2 and ACF because the metabox API is a soggy paper bag of wet hair -- core should fix that)

**Comment by mintplugins** [comment]
Just a few more thoughts I have (apologies for the wall of text). 

I am definitely not in favour of ads being plastered all over. But the hard part about trying to enforce a "no ads" policy is that it is subjective. 1 person might see it as an ad, and another might not. Sometimes the way we understand words like "advertisement" can depend on our worldview and experience, just like all words. Words can be like "bowls" a lot of the time: we all pour our own meaning into that bowl, and often expect everyone else to have that same understanding of the word. 

The initial proposed change requires a human to make a subjective decision about what is-or-isn't an advertisement, and opens the ecosystem up to potentially-unfair outcomes. Today the person making the decision (like @Ipstenu or @Otto42) could think the Yoast ad is fine or not fine, and 10 years from now a new person might not see it the same way. Or say someone gets really creative and develops some totally new way of showing an advertisement that puts it in a grey area. Comparing that ad with the Yoast ad will be tough. 

This is why I think the guidelines should try and be non-subjective wherever possible. In my proposal above (which is only one-of-many possible ideas), I meant for it to take away most of the subjectivity away because adding a notification indicator with a standardized style is either there, or it is not. I feel like it's pretty clear whether you followed the guidelines, or you didn't. 

A notification indicator would also require you to "own" your advertisement and its purpose. I feel like that might lead some people/plugins to re-think what they put there. 

For example, to the untrained eye/user, the Yoast ad could appear like it came from WordPress itself; like WordPress is recommending the Yoast sale. But with a notification indicator, it becomes very clear who put the notification/ad there, and what their intention with that ad is. I think that in itself will make people re-think how intense they get there. 

While the notification API is a great step forward, I'm not certain it would address the issue of ads showing up in `admin_notices`, as that is still going to catch people's eye the most, so people will still do it. This is the only reason I think a guideline should still exist for those in some way. 

Also, this entire situation will likely make people re-think what they put there (if they are aware of it). Yoast SEO has multiple pages of 1 star reviews coming in right now because of this, which kind-of shows that the system is working. The punishment for their behaviour came from the users themselves, not from a higher-up governing body.

**Comment by Otto42** [comment]
> This is why I think the guidelines should try and be non-subjective wherever possible. 

Respectfully, I disagree. The guidelines should absolutely be subjective and up for human interpretation. Because that gives the team the greatest flexibility in doing the right thing, and also because human judgement is valuable and should not be so easily discarded.

If the action is right but the rule says it is not, then the rule is wrong. We will not submit to explicit and unbreakable rule-making while I am a member of this community. Freedom matters more. 

Yeah, you may not like ads. That's okay. Don't use plugins that have them. This is your choice. Plugin authors are not your slaves destined to work for free. Ads are acceptable. Being malicious isn't. A banner ad on the dashboard that you can click an X to make go away isn't the end of the world, and yes, it will be allowed.

Closed

**Comment by jessuppi** [comment]
This discussion is hilarious, and I"m sure Otto will ban me after I comment...

> Not all plugins (in fact, not most plugins) have admin panels. This sort of guideline change would result in an unfair advantage in business being handed over to only the plugins with their own panels. -- @Ipstenu

100% true, it would punish more lightweight plugins.

> Adding a settings panel to a plugin isn't rocket science, in the grand scheme of things. -- @jfarsen 

Advocating for more bloat, and more database queries, is a fool's errand.

> Also the line between an ad and an alert is so wafer thin, that it requires a lot of human work to manage and monitor. Work no one is willing to do on an extended basis. -- @Ipstenu

100% false. Many people, including myself, have repeatedly offered to help out the "horribly overworked volunteers" at WordPress.org. You can't condescend to users with moral authority and then fail to be transparent about the fact that your team is a small group of paid employees from Automattic and Audrey Capital. The WordPress Foundation has zero employees.

There are also obvious ways to improve the rules to allow for advertising, but to specify what types of advertising is obtrusive, misleading, and disallowed...

> @Otto42 Could you link us 3 tweets or 3 comments somewhere where people are happy with this banner? I'll leave you alone. Thank you. -- @JulioPotier 

There is no point arguing, the intellectual dishonesty and word games are just a facade to protect Matt's business partners from any repercussions. Otto is just a soldier.

> The guidelines should absolutely be subjective and up for human interpretation. Because that gives the team the greatest flexibility in doing the right thing, and also because human judgement is valuable and should not be so easily discarded. If the action is right but the rule says it is not, then the rule is wrong. We will not submit to explicit and unbreakable rule-making while I am a member of this community. Freedom matters more. -- @Otto42 

Otto of Arc has spoken. _Freedom!!!_ (screamed in a Scottish accent, right after you've banned dozens of smaller plugin agencies for doing the same exact things that Yoast does weekly)

**Pull request closed without merging**
